### ISSUE TITLE
malpediaEvalScriptOutput file not being written to, causing null pointer exceptions

### ISSUE THREAD

**Issue by seanmahoney** [fxb-cocacoding/yara-signator#6] opened 2021-04-06 19:13 UTC
Hi, I keep getting null pointer exceptions from the function getNgramsForFamily_NextGen_CandidateOne, in NgramCreator. I believe this is due to data not being written to the malpediaEvalScriptOutput file that I have specified in yarasignator.conf. I checked the permissions for this file and they are not an issue.  If you have run into this problem before and  know how to fix it, or if you could point me in the right direction to check (for example, which class or function is responsible for writing to this file), it would be greatly appreciated. 

Thank you

**Comment by fxb-cocacoding** [comment] 2021-05-20 14:54
Hi,

just saw this issue today, sorry for the late reply.
I will try to reproduce this error and fix it in the next version.
Could you post your version, .yarasignator.conf file and the malware repository file structure?

Best regards,
Felix

**Comment by seanmahoney** [comment] 2021-05-21 21:53
Hi,

No problem at all. I appreciate the response.
I actually received the error with both Yara Signator 0.5.0 and  0.6.0 so it's likely something I'm doing wrong on my end. I'm using Malpedia's repo and have not altered it in any way. 
My conf file is as follows:
![image](https://user-images.githubusercontent.com/28372734/119201489-6726ee80-ba65-11eb-944f-9bf7d13225d4.png)
![image](https://user-images.githubusercontent.com/28372734/119201562-8aea3480-ba65-11eb-918d-8b376dfca66c.png)
![image](https://user-images.githubusercontent.com/28372734/119201583-95a4c980-ba65-11eb-9793-901df37a4058.png)
If you need any further info, please let me know.

Thanks a lot,
Sean

**Comment by seifreed** [comment] 2021-11-04 09:54
any update on this issue?

**Comment by fxb-cocacoding** [comment] 2021-11-05 20:46
Yes, I do a new release in the next weeks and bring some docker files and an exemplary directory structure. This should prevent such errors because I guess this has something to do with different setups, versions, directory locations etc.
I could not reproduce this error and maybe its gone if the new release has a clearer structure.

**Comment by seifreed** [comment] 2021-11-05 22:42
This sounds super! Thanks for continue developing the tool

**Comment by fxb-cocacoding** [comment] 2022-04-11 18:38
Hi, a demo release with exemplary directory structure is now available in the docker folder.
You need to install sudo, docker and docker-compose to execute the script in `docker/execute_demo.sh`.

How it works:
The docker-compose file for testing creates a test infrastructure and downloads a possible goodware archive.
A malware sample pool is already available in the malpedia.zip folder.
Then, malware and goodware is processed into smda reports with the correct meta information we need in order to process the reports with YARA-Signator.
As the goodware repo is quite large (but also realistic, it contains the empty MSVC projects created by Daniel Plohmann, https://github.com/danielplohmann/empty_msvc), you can estimate that the project needs 30 min to about 2 h depending on the hardware.

Sorry for the late reply, I was busy with some other side projects. With the new docker files the project should finally be a bit better and more intuitive to use. If you have any further questions feel free to contact me. If the docker files throw some errors feel free to just open another issue. As the setup is now more stable I would close this issue but I can reopen it if the solution is not working.

**Closed as completed by fxb-cocacoding** 2022-04-11 18:38 UTC
