### ISSUE TITLE
Filter sequences that will likely yield YARA atoms of low quality

### ISSUE THREAD

**Issue by danielplohmann** [fxb-cocacoding/yara-signator#2] opened 2020-09-24 12:24 UTC
Rules generated with `yara-signator` may trigger a warning by YARA that certain sequences are of inferior quality:
```
$ yarac test.yar test.yac
test.yar(3): warning: $sequence_0 is slowing down scanning
$ grep sequence_0 test.yar
  $sequence_0 = { 68???????? e8???????? 68???????? e8???????? bb???????? 53 }
```
This warning is triggered when sequences do not fulfill the minimum quality for atoms (i.e. matching terms used in YARA).
The default minimum atom length according to the YARA source code is 4.
I think the warning message could be avoided if only such sequences are selected by `yara-signator` that have a minimum sequence of 3 or 4 concrete byte values as a continuous sequence. 
For the above example, instead going for a sequence like 
```
$sequence_0 = { 68???????? e8???????? bb???????? 53 52 51}
```
already does the trick.
This requirement could be easily added as a further filter stage.

**Comment by fxb-cocacoding** [comment] 2020-10-15 14:25
Thanks for reporting, the issue is fixed in version 0.5.0.

**Closed as completed** 2020-10-15 14:26 UTC
